# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
baseurl: "" # the subpath of your site, e.g. /blog
url:                'https://foursixnine.io/' # The base hostname & protocol for your site

title: foursixnine's lair
name: Santiago Zarate
email: santiago+blog AT zarate.co
tagline: "Abandon all hope!"
description: "I do free and opensource software. I eat. I travel. I take pictures. I bike. I love linguistics."
origin: "I'm from Caracas, Venezuela"

twitter: foursixnine
github:  foursixnine
devto: foursixnine
facebook: foursixnine
flickr:   foursixnine
instagram: foursixnine
linkedin: foursixnine
telegram: foursixnine
keybase: foursixnine

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# GitLab instances
# gitlab:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.co

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
