# General Jekyll Config
url: https://foursixnine.io
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
destination:  _site/
plugins_dir:  lagom/_plugins/
layouts_dir:  lagom/_layouts/
includes_dir: _includes/
exclude:
  - lagom/
data_dir: _data

source:          .
#plugins_dir:     _plugins
layouts_dir:     lagom/_layouts
includes_dir:    lagom/_includes
