# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
baseurl: "" # the subpath of your site, e.g. /blog
url:                'https://foursixnine.io/' # The base hostname & protocol for your site

title: foursixnine's lair
author:
  name: Santiago Zarate
  email: blog AT foursixnine.io
description: ""
I'm a self-taught engineer or a hacker, depending on the question you ask; I love to solve problems of different sorts, coach, mentor, and guide; with almost 20 years of experience in 2022, I'd like to offer the perspective, knowledge, and expertise to those who'd like to tap into it.

Working with [Humans Not Robots](https://humansnotrobots.net), I can help with the soft skills side of your career and interview preparation, including improvements to your CV, along with Quality Engineering, IT Career Guidance, and Leadership Coaching. Furthermore, I offer Mentorships and Coaching for neurodivergent people, especially for those who are part of the ADHD tribe and the Autistic Spectrum Disorder tribe, tribes I belong to.

During the day, I'm passionate about Quality Engineering, Software Development Lifecycle, Product Management, Open Source software, and communities.

If you would like to talk, please send an [email](mailto:info@foursixnine.io), or chat with me on [Telegram](https://t.me/foursixnine).
origin: "I'm from Caracas, Venezuela"
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: foursixnine
    github:  foursixnine
    devto: foursixnine
    facebook: foursixnine
    flickr:   foursixnine
    instagram: foursixnine
    linkedin: foursixnine
    telegram: foursixnine
    keybase: foursixnine

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# GitLab instances
# gitlab:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.co

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
